# These are supported funding model platforms

custom: ['https://www.paypal.com/donate?hosted_button_id=TY8P8THDK9AJG', 'https://send.monobank.ua/5GTdpdCeWE', 'https://yoomoney.ru/to/4100116306429482']
